{
  ["jsonapi"] = {
    ["name"] = "JSON-API",
    ["author"] = "ElvishJerricco",
    ["purl"] = "http://www.computercraft.info/forums2/index.php?/topic/5854-json-api-v201-for-computercraft/",
    ["location"] = "https://raw.githubusercontent.com/fishermedders/cc/master/jsonapi",
    ["target"] = "/bin/util/json",
    ["notes"] = {},
    ["dependencies"] = {},
    ["category"] = "Utility",
  },
  ["luaide"] = {
    ["name"] = "LuaIDE",
    ["author"] = "GravityScore",
    ["purl"] = "http://www.computercraft.info/forums2/index.php?/topic/12347-luaide-10-you-might-actually-like-editing-in-game/",
    ["location"] = "http://pastebin.com/raw/vyAZc6tJ",
    ["target"] = "/opt/LuaIDE",
    ["notes"] = {
      "Also a treause disk as of CC 1.5"
    },
    ["dependencies"] = {},
    ["category"] = "Utility",
  },
  ["brc"] = {
    ["name"] = "Big Reactors Control",
    ["author"] = "jared314",
    ["purl"] = "http://pastebin.com/p4zeq7Ma",
    ["location"] = "http://pastebin.com/raw/p4zeq7Ma",
    ["target"] = "/opt/brsetup",
    ["notes"] = {},
    ["dependencies"] = {},
    ["category"] = "Utility",
  },
  ["npaintpro"] = {
    ["name"] = "NPaintPro",
    ["author"] = "nitrogenfingers",
    ["purl"] = "http://www.computercraft.info/forums2/index.php?/topic/5029-145-npaintpro/",
    ["location"] = "http://pastebin.com/raw/pzWSRqNF",
    ["target"] = "/opt/npaintpro",
    ["notes"] = {},
    ["dependencies"] = {},
    ["category"] = "Utility",
  },
  ["f4t"] = {
    ["name"] = "Fallout 4 Terminal",
    ["author"] = "savior67",
    ["purl"] = "http://www.computercraft.info/forums2/index.php?/topic/10978-fallout-terminal/",
    ["location"] = "http://pastebin.com/raw/JmHGRsww",
    ["target"] = "/opt/f4t",
    ["notes"] = {},
    ["dependencies"] = {},
    ["category"] = "Fun",
  },
  ["frp"] = {
    ["name"] = "Fisher Rednet Protocol",
    ["author"] = "Fisher Medders",
    ["purl"] = "fishermedders.com",
    ["location"] = "http://pastebin.com/raw/v7ZwP8GE",
    ["target"] = "/bin/util/frp",
    ["notes"] = {},
    ["dependencies"] = {},
    ["category"] = "Utility",
  },
}
